# Generated by Django 4.1.7 on 2023-03-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserAPI", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="lastname",
            new_name="last_name",
        ),
    ]
